apiVersion: v1
kind: service
metadata:
  name: mynodeportservice
spec:
  type: nodedPort
  selector:
    app: myapp
ports:
 - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
